[2019-Mar-03 20:53] 176.99.175.200 GET https /ar/? 302 FOUND
[2019-Mar-03 20:53] 176.99.175.200 GET https /ar/? 302 FOUND
[2019-Mar-03 20:54] 176.99.175.200 GET https /ar/? 302 FOUND
[2019-Mar-03 20:54] 176.99.175.200 GET https /ar/login?next=%2Far%2F 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/apps/xnoobs/app/ar_server/views.py", line 68, in login
    return render_template('login.html', form=login_form)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/apps/xnoobs/app/templates/login.html", line 29, in top-level template code
    {{ form.button(class_='login-button') }}
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 283, in __call__
    return super(SubmitInput, self).__call__(field, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 184, in __call__
    return HTMLString('<input %s>' % self.html_params(name=field.name, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 71, in html_params
    params.append('%s="%s"' % (text_type(k), escape(text_type(v), quote=True)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

[2019-Mar-03 21:00] 176.99.175.200 GET https /ar/? 302 FOUND
[2019-Mar-03 21:00] 176.99.175.200 GET https /ar/login?next=%2Far%2F 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/apps/xnoobs/app/ar_server/views.py", line 68, in login
    return render_template('login.html'.encode('utf-8'), form=login_form)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/apps/xnoobs/app/templates/login.html", line 29, in top-level template code
    {{ form.button(class_='login-button') }}
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 283, in __call__
    return super(SubmitInput, self).__call__(field, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 184, in __call__
    return HTMLString('<input %s>' % self.html_params(name=field.name, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 71, in html_params
    params.append('%s="%s"' % (text_type(k), escape(text_type(v), quote=True)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

[2019-Mar-03 21:00] 176.99.175.200 GET https /ar/? 302 FOUND
[2019-Mar-03 21:00] 176.99.175.200 GET https /ar/login?next=%2Far%2F 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/apps/xnoobs/app/ar_server/views.py", line 68, in login
    return render_template('login.html'.encode('utf-8'), form=login_form)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/apps/xnoobs/app/templates/login.html", line 29, in top-level template code
    {{ form.button(class_='login-button') }}
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 283, in __call__
    return super(SubmitInput, self).__call__(field, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 184, in __call__
    return HTMLString('<input %s>' % self.html_params(name=field.name, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 71, in html_params
    params.append('%s="%s"' % (text_type(k), escape(text_type(v), quote=True)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

[2019-Mar-03 21:00] 176.99.175.200 GET https /ar/login?next=%2Far%2F 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/apps/xnoobs/app/ar_server/views.py", line 68, in login
    return render_template('login.html'.encode('utf-8'), form=login_form)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/apps/xnoobs/app/templates/login.html", line 29, in top-level template code
    {{ form.button(class_='login-button') }}
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 283, in __call__
    return super(SubmitInput, self).__call__(field, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 184, in __call__
    return HTMLString('<input %s>' % self.html_params(name=field.name, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/wtforms/widgets/core.py", line 71, in html_params
    params.append('%s="%s"' % (text_type(k), escape(text_type(v), quote=True)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

[2019-Mar-03 21:02] 176.99.175.200 GET https /ar/? 302 FOUND
